[tool.pyright]
include = ["src"]
exclude = ["**/node_modules",
    "**/__pycache__",
]
defineConstant = { DEBUG = true }
typeCheckingMode = "basic"

pythonVersion = "3.9"

[tool.black]
line-length = 100
